export enum StatusInvoiceEnum {
  'PENDING' = 'PENDING',
  'VALIDATED' = 'VALIDATED',
  'CANCELED' = 'CANCELED',
  'EXPIRED' = 'EXPIRED',
  'REFUNDED' = 'REFUNDED',
  'FAILED' = 'FAILED',
  'REJECTED' = 'REJECTED',
}
