export enum UserRoleEnum {
  PUBLIC = 'PUBLIC',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  COMPANY_ACCOUNT = 'COMPANY_ACCOUNT',
  COMPANY_EMPLOYEE_ACCOUNT = 'COMPANY_EMPLOYEE_ACCOUNT',
  PREMIUM_ACCOUNT = 'PREMIUM_ACCOUNT',
}
