name: preprod CI

on:
  push:
    branches: [ preprod ]

  pull_request:
    branches: [ preprod ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.2.0]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.2.0]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
  docker:
    name: Build - Docker
    runs-on: ubuntu-18.04
    needs: [ run_tests, build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/api-walletshare:preprod

  deploy_server:
    name: Deploy - Docker - serveur
    runs-on: ubuntu-18.04
    needs: [ docker]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Trigger API Webhook reload service
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: ${{ secrets.WEBHOOK_URL }}
